spring:
    application:
        name: libraryapi
    datasource:
        url: jdbc:postgresql://localhost:5432/library
        username: postgres
        password: admin
        driver-class-name: org.postgresql.Driver
    jpa:
        show-sql: true
        hibernate:
            # ddl-auto: update #opcao "update" ele cria atraves da classe - usar somente em desenvolvimento pois geralmente coloca permissao para executar ddl(data definiiton language)
            ddl-auto: none
        properties:
            hibernate.format_sql: true #apos colocar show-sql  format ajuda na melhor visualiaçao do codigo sql no console

